CREATE TABLE IF NOT EXISTS `{table}`(
	`id` INTEGER AUTO_INCREMENT,
	`uuid` VARCHAR(36) UNIQUE NOT NULL,
	`status` BOOLEAN DEFAULT true,
	`texture` TINYTEXT,
	`space` BIGINT NOT NULL,
	`partners` LONGTEXT NOT NULL,
	`filter` LONGTEXT NOT NULL,
	`unfilter` LONGTEXT NOT NULL,
	PRIMARY KEY(`id`)
)