CREATE TABLE IF NOT EXISTS `{table}`(
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`uuid` VARCHAR(36) UNIQUE NOT NULL,
	`status` BOOLEAN DEFAULT true,
	`texture` TINYTEXT,
	`space` BIGINT NOT NULL,
	`partners` TEXT NOT NULL,
	`filter` TEXT NOT NULL,
	`unfilter` TEXT NOT NULL
)