name: Build & Publish

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Get changelog
        id: changelog
        run: |
          {
            echo "changelog<<EOF"
            cat CHANGELOG.md
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Release
        uses: HSGamer/MCReleaser@master
        with:
          files: target/ExtraStorage.jar
        env:
          DESCRIPTION: ${{ steps.changelog.outputs.changelog }}
          GAME_VERSIONS: "1.16..latest"

          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          MODRINTH_PROJECT: 4gAxJhPV
          MODRINTH_LOADERS: |
            bukkit
            spigot
            paper
            purpur
            folia

          VOXELSHOP_KEY: ${{ secrets.VOXELSHOP_KEY }}
          VOXELSHOP_RESOURCE: 860

          DISCORD_URL: ${{ secrets.DISCORD_URL }}
          DISCORD_MENTIONS: "1224672188473544735"
          DISCORD_LINKS: |
            {
              "SpigotMC": "https://www.spigotmc.org/resources/extrastorage.90379/",
              "Modrinth": "https://modrinth.com/plugin/extrastorage-plugin"
              "voxel.shop": "https://voxel.shop/product/860/extrastorage"
            }

      - name: "GitHub Release"
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false